spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_demo?useUnicode=true&characeterEncoding=utf-8&serverTimezone=UTC
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.xxx.demo.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  level:
#    com.xxx.demo.mapper: debug
